spring:
  application:
    name: github-user-service

  cache:
    type: simple

server:
  port: 8080

github:
  api:
    connect-timeout: 2000
    read-timeout: 5000

resilience4j:
  retry:
    instances:
      github:
        max-attempts: 3
        wait-duration: 500ms

logging:
  level:
    com.example.github_user_service: INFO
